### ISSUE TITLE
maven（pom.xml）とgradleの併用のお願い

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#10]
お疲れさまです。

単体テスト（モック＋スタブ）を、一部だけお手伝いしようかと思いましたが、gradleが通らないため（おそらくバージョン差、プラットフォーム差が原因）、着手ができない状況です。pom.xmlをgradleから生成するか、おそらく元々あったpom.xmlをもとに戻して頂けると助かります。

参考
- http://153.121.74.135/bugzilla/show_bug.cgi?id=9

**Comment by inotakuya** [comment]
お疲れ様です。
pom.xmlをgradleから生成しました。
確認お願い致します。

**Comment by athenaeum-school** [comment]
結論からすると動きましたが、classpathが直指定なので、ダウンロードする側は、project -> property -> build path でライブラリーを除去して、Maven Dependenciesを選択する必要がありました。ダウンロード頂いてもすぐには使えない状況というのは今いちな気がします。

**Comment by inotakuya** [comment]
かしこまりました。
eclipseでclasspathの設定を変更してみます。
