### ISSUE TITLE
inotakuya/Shoppingsite とのレポジトリ間のマージ（サブツリー等）

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#12]
https://github.com/inotakuya/Shoppingsite

確認したところ、Shoppingsiteでは、単体テストが部分的ながらも、できているので、こちらをVeggieMarketのコンポーネント（サブプロジェクト）として、統合すべきと考えますが、ご検討をお願いします。

**Comment by athenaeum-school** [comment]
レポジトリ間の結合ですが、

http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

を参照すると結合ができるようです。

履歴を結合できるので裏技に近いですが、これができれば、相当時間を節約できると考えます。

**Comment by athenaeum-school** [comment]
この方法ですと、CustomerModelについても、レポジトリごと統合できそうなので、分散・拡散したプロジェクトを一つに統合しましょう。

**Comment by inotakuya** [comment]
情報ありがとうございます。
これらを参考にして、レポジトリを統合してみます。
