### ISSUE TITLE
ざっとしたスケジュールと優先順位

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#13]
大きなプロジェクトなので、優先順位別でスケジュールを作ることは可能でしょうか。

一応、今後の課題としては、監査、監視機能や不可分散、キャッシングを考えています。技術指導タイミングの前提として、プロジェクトがスタブを使った状態でもよいので、全て稼働していることが必要となってしまうわけです。

ということで、ある程度、スケジュールが判明した段階での情報共有いただき、おりよいときに方針・方法論は紹介するという流れでいこうかとおもいます。さらに、readme.mdか、本スレでもいいので、スケジュールや仕様を変更したらアナウンスして頂けるとたすかります。

**Comment by inotakuya** [comment]
わかりました。スケジュールが決まり次第連絡いたします。
