### ISSUE TITLE
RESTではないので修正したほうが良い点

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#2]
backboneの話をした際に？な点がありましたので、ソースをチェックしました。

ソースをみて気づいた点として、RestControllerについて無理がある印象があります。Nadd32氏のUnityゲームプロジェクトでは、RESTを使いこなしておりましたし理解されていたと思いますので、スルーしておいてよいかもと考えたのですが、TDDの段階までくると、SpringMVCのサーブレット機能を使うのは、むしろ難しいのではないかと考えます。JavascriptとのXMLかJSONでの通信に修正頂くようご検討ください。

基本的には、backbone.jsを使うウェブサービスでは、クライアントには静的HTMLが一番シンプルなので、index.html一つだけでも、問題ないと考えます。index.htmlのjavascriptとの通信なので、無理矢理Springのモジュールと連携すると、アーキテクチャー的に無理がくると考えます。

**Comment by inotakuya** [comment]
わかりました。修正します。
