### ISSUE TITLE
プロジェクトのてこ入れ

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#3]
このプロジェクトは潜在的には大きく広げられる可能性があると思うので、今後の進め方についての提案です。
- 開発環境サーバーはnode.jsに変更（Springだと色々面倒ですし、しかし最終的なバックエンドにはSpring）
- Gruntを活用したビルドの自動化
- Jasmine/SinonJS/QUnitなどのテストフレームワークの活用
- RequireJS/AMDなどによるコードの簡略化
- 認証、チャット、リアルタイムアップデートの導入（将来的なもの）

以上です。ご検討ください。

**Comment by inotakuya** [comment]
わかりました。
