### ISSUE TITLE
RabbitMQ (middleware) + Node.js/MongoDB or Redis (front) + Spring Integration (middleware) + Spring (backend)

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#5]
Node.js+ RabbitMQについてはSTOMPで通信する方法を昨日お話しましたが、その他にはAMQPクライアントを使う方式、
- http://www.squaremobius.net/rabbit.js/
- https://github.com/postwait/node-amqp

があるようです。

TOEICの勉強もあるでしょうから、大変だとは思いますが、このプロジェクトは実力を証明するにはちょうどよい難易度（かつ、このアーキテクチャは新しいので、コピペでない証明という意味も）かと思います。おおむね５週間程度かけて完成するのが、英語の勉強を考えるとちょうどよいスケジュールかなと思います。

講座的にはまだカバーしていない点として、node.js+socket.ioなどを使ったリアルタイムアプリ（チャットなど）やサーバー再度のnotifications、Springでの認証（データベース認証のことです）や、Camel/RabbitMQ/Cloud Foundryをカバーすべきかとは思っています。

また、アプリについては、Shipping（発送・アプリ＋アイテム配信） / Payment（課金）/ Audit（監査・ログ）/ などのサービスをSOA環境で動作させるよう設計してみてください。

その他にも、Spring Batchやスケジュールを使った、メンテナンスなどを考えてみてください。

最後に、本プロジェクトが最良とは考えていませんので、例えば以前考案されたShoppingSiteプロジェクトの詳細設計＋実装（Broadleaf Commerceの取り込みでも良かったのですが・・・）、SOA化の推進が着実にできるのであれば、それでも構いません。

マンネリ化して思考停止になり成長が止まってしまうことが一番怖いと考えますので、ご提案させて頂いているというのが本プロジェクトの趣旨です。

**Comment by inotakuya** [comment]
まずRabbitMQを使った実装を考えてみようと思います。
node.js+socket.ioなどを使ったリアルタイムアプリ（チャット）は興味があるので、勉強しておきます。

**Comment by athenaeum-school** [comment]
> > node.js+socket.ioなどを使ったリアルタイムアプリ（チャット）は興味があるので、勉強しておきます。

本アーキテクチャーの提案は、あくまでエンタープライズ環境での実装の経験をして頂くためなので、現在のプランで十分に野心的と考えますが、いかがでしょうか。

リアルタイムアプリ（チャット）などはAPIの問題なので、結構簡単に作れます。ですので優先順位は最低（＝勉強しない）とすることをを強くおすすめします。優先順位としては
- 各コンポーネントでの機能テスト（サービス・アプリケーションレイヤー）の実施
- 下層レイヤー、特にRepositoryやトランザクションの単体テストの終了
- メッセージキューの双方向での実装（Sender/Reciever(subscriber)）およびテスト
- DBスキーマ＝ドメイン・オブジェクトモデルの設計および実装
- Spring Integrationを使った単体＋結合テスト
- readme.mdでの分かりやすい解説、マニュアル

が高いと考えます。興味と優先順位は必ずしも等号しないと思うので、貴重な時間は大切にすべきですよ。

**Comment by inotakuya** [comment]
わかりました。テスト関係を優先に進めていきます。

**Comment by athenaeum-school** [comment]
node.js+socket.ioについてはお互い忘れているぐらい小さなスクリプトを１月前に
紹介済みのようです。確認頂ければ、その程度の内容です。（STOMP+SockJSについてもスカイプで話せるぐらいの内容ですし、設計やアーキテクチャーが決定した後はスムーズに実装できそうですね。ただその設計やアーキテクチャーが一番重要なんですけどね。）

確か、node.js側での認証APIやbackboneとsocket.ioを組み合わせるようなことを予定したと思うのですが、Springの基礎力を高めるために中止したという経緯と記憶してます。

ということで、node.js＋socket.io実装は、SOA環境の実装が完了するまでは中止でお願いします。（優先順位に含めない）

**Comment by inotakuya** [comment]
わかりました。node.js＋socket.ioの実装は一旦中止にします。
