### ISSUE TITLE
tomcat plugin for SOA

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#6]
pom.xmlのtomcat pluginの項目で

``` xml
<configuration>
<port>8081</port>
</configuration>
```

とすればポートを使い分けられるので、試してみてください。

**Comment by athenaeum-school** [comment]
tomcatやpluginのバージョンで動かないことがあるので

mvn -Dmaven.tomcat.port=8081 package tomcat:run-war

もお試しください。

**Comment by inotakuya** [comment]
build.gradleでport番号を変更できるみたいなのでgradleで実装しようと思っています。

**Comment by athenaeum-school** [comment]
今のgradle設定だけみると、ポート番号が一つしか指定されていないので、実際の分散環境（各warファイルは別サーバーに配置）だと稼働しないと思いますが、修正するとの理解でよろしいですか？（Readme.mdにマニュアルがないんで、私の理解もいまいちではあるんですがね）

今はテスト目的ということかとは思いますが、結合テストの段階では手間取るようなら、最も簡単に動く設定で動かすとよいかもしれないです。

**Comment by inotakuya** [comment]
すいません。まだ実装していないです。修正する予定です。

**Comment by athenaeum-school** [comment]
アドバイスです。tomcatはいらないのではないでしょうか？（tomcatをここまで使いこなそうとする応用力＋執念には感服はするものの）

``` groovy
apply plugin : 'jetty' 
```

``` bach
$ gradle jettyRunWar
```

だけのほうが、テスト環境にはいいと思いますが、これだと駄目な理由はありますか？

**Comment by inotakuya** [comment]
わかりました。
apply plugin : 'jetty' に変更します。

**Comment by athenaeum-school** [comment]
ご検討いただきありがとうございます。
そもそも論として、gradleからコンテナ起動が必要なのかも議論の余地はある気がします。
サーバーの特定ディレクトリーをクリーンして、warファイルをコピーするぐらいが普通のやりかたと思う次第です。
※Antのbuild.xmlでやっていたことに近い感じで理解すると良いかもです。
