### ISSUE TITLE
crow’s notation, Shipping/Payment/Customer ERD

### ISSUE THREAD

**Issue by athenaeum-school** [inotakuya/VeggieMarket#7]
お疲れ様です。

SOA環境の実装についてですが、各コンポーネントアプリケーションについての参考資料として、Broadleaf Commerceの図をご案内いたします。

notation (ERD - Entity Relationship Diagram)
- https://conceptdraw.com/a672c3/preview--Design%20elements%20-%20ERD%20(crow's%20foot%20notation)

Order@Broadleaf Commerce (Shipping + Payment)
- http://www.broadleafcommerce.com/docs/core/current/database-model/order-model

Customer@Broadleaf Commerce
- http://www.broadleafcommerce.com/docs/core/current/database-model/customer-model

なお、Taxなど現時点で不要と考える場合は内容を減らして、適合させることも可能かと思います。

Shippingについては、最後のendpoint/out-channelをSMTP（配達部門へのメール）配信にするだけでも実用性は担保できると考えます。

**Comment by inotakuya** [comment]
ありがとうございます。Broadleaf Commerceを参考に考えてみます。

**Comment by athenaeum-school** [comment]
mysql workbenchも忘れないようにお願いします。

**Comment by inotakuya** [comment]
わかりました。
